### ISSUE TITLE
Enabling CORS

### ISSUE THREAD

**Issue by bhrzk** [nullism/pycnic#25]
Hi, 
I'm having trouble to enable CORS in one simple pynic script. The front-end sends OPTIONS and seems Pycnic block it so the API stops working. 

Thanks.

**Comment by nullism** [comment]
Hi there!

That's interesting.

Could you tell me if all methods are blocked cross-site, or just OPTIONS? For example, if making a cross-site GET, does this get blocked?

Also, are you setting an "Access-Control-Allow-Origin" header?

Thanks! Just let me know and I can dig into this more.

**Comment by bhrzk** [comment]
Hi, 
yes I get Access-Control-Allow-Origin error. I never passed that options so I don't know what will happen. 
I checked with postman and even browser is okay but when it gets into React it returns error and I have this error on the server : 
 "OPTIONS /network/get/list HTTP/1.1" 405 120

I'm okay if somehow I can set "*" in the script but I don't know how and where. 

Thanks.

**Comment by nullism** [comment]
Hi again,

Do you have `def options(self)` on your Handler?

I tested this example and it appears to be working:

```python
#!/usr/bin/env python3
from pycnic.core import WSGI, Handler

class CorsTest(Handler):

    def get(self):
        return {
            "message": "Cross site works!",
            "origin": self.request.get_header("Origin")
        }

    def options(self):
        return {
            "GET": {
                "description": "Test cross site origin",
                "parameters": None
             }
        }


class app(WSGI):

    # This allows * on all Handlers
    headers = [("Access-Control-Allow-Origin", "*")]

    routes = [
        ("/", CorsTest()),
    ]

if __name__ == "__main__":

    from wsgiref.simple_server import make_server
    try:
        print("Serving on 0.0.0.0:8080...")
        make_server('0.0.0.0', 8080, app).serve_forever()
    except KeyboardInterrupt:
        pass
    print("Done")

```

The part `headers = [("Access-Control-Allow-Origin", "*")]` allows CORs from any Origin by setting that header globally. You can set a header for a specific resource with `self.response.set_header`. 

The `def options(self)` method returns JSON-based options for your resource.  If you do not have `options` defined on a resource, it will return a 405 Method Not Allowed response by design, since it's not implemented.

Let me know if that fixes the issue for you. Thanks!

**Comment by bhrzk** [comment]
Thanks, I'll give it a try

**Comment by bhrzk** [comment]
Hi
Thanks, 
this "headers = [("Access-Control-Allow-Origin", "*")]" saved my life.

**Comment by nullism** [comment]
Glad I could help! Happy coding!
